const GET_FEATURED_MOVIE = 'GET_FEATURED_MOVIE';
const GET_FEATURED_MOVIE_SUCCESS = 'GET_FEATURED_MOVIE_SUCCESS';
const GET_FEATURED_MOVIE_FAIL = 'GET_FEATURED_MOVIE_FAIL';

export { GET_FEATURED_MOVIE, GET_FEATURED_MOVIE_SUCCESS, GET_FEATURED_MOVIE_FAIL };
